ALTER TABLE capex_project
    ALTER COLUMN surface TYPE DOUBLE PRECISION USING surface::DOUBLE PRECISION;

ALTER TABLE capex_project
    ALTER COLUMN budget TYPE DOUBLE PRECISION USING budget::DOUBLE PRECISION;

ALTER TABLE capex_project
    ALTER COLUMN transport_rate TYPE DOUBLE PRECISION USING transport_rate::DOUBLE PRECISION;

ALTER TABLE capex_project
    ALTER COLUMN douane_rate TYPE DOUBLE PRECISION USING douane_rate::DOUBLE PRECISION;

ALTER TABLE capex_project
    ALTER COLUMN port_rate TYPE DOUBLE PRECISION USING port_rate::DOUBLE PRECISION;

ALTER TABLE capex_project
    ALTER COLUMN local_rate TYPE DOUBLE PRECISION USING local_rate::DOUBLE PRECISION;

ALTER TABLE capex_project
    ALTER COLUMN margin_rate TYPE DOUBLE PRECISION USING margin_rate::DOUBLE PRECISION;

ALTER TABLE capex_project
    ALTER COLUMN risk_rate TYPE DOUBLE PRECISION USING risk_rate::DOUBLE PRECISION;

ALTER TABLE capex_project
    ALTER COLUMN import_threshold TYPE DOUBLE PRECISION USING import_threshold::DOUBLE PRECISION;
